version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST:-172.17.0.1}

  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./html:/var/www/html
    depends_on:
      - php
