version: '3'

services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mediawiki_data:/var/www/html
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      MW_DB_TYPE: mysql
      MW_DB_USER: ${DB_USER:-root}
      MW_DB_PASSWORD: ${DB_PASSWORD:-root}
      MW_DB_SERVER: db:3306
      MW_DB_NAME: ${DB_NAME:-my_wiki}
      MW_SITE_SERVER: ${SITE_URL:-https://localhost}
      MW_SITE_NAME: ${MW_SITE_NAME:-My Wiki}
      MW_SITE_LANG: en

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-my_wiki}

  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - mediawiki

volumes:
  mediawiki_data:
  db_data:
