version: '3'

services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- mediawiki_data:/var/www/html
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      DB_SERVER: ${DB_SERVER:-db}
      DB_NAME: ${DB_NAME:-my_wiki}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-MyStrongPassword123!}
      DB_PORT: ${DB_PORT:-5432}
      MW_SITE_SERVER: ${SITE_URL:-https://localhost}
      MW_SITE_NAME: ${MW_SITE_NAME:-My Wiki}
      MW_SITE_LANG: en
    depends_on:
      - db
      #- maintenance

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-MyStrongPassword123!}
      POSTGRES_DB: ${DB_NAME:-my_wiki}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - mediawiki

#  maintenance:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - mediawiki_data:/var/www/html
#      - ./LocalSettings.php:/var/www/html/LocalSettings.php
#      - ./docker-entrypoint.sh:/docker-entrypoint.sh
#    env_file:
#      - .env
#    entrypoint: /docker-entrypoint.sh
#    stdin_open: true
#    tty: true

volumes:
  #mediawiki_data:
  postgres_data:
